`timescale 1ns/1ps
`default_nettype none

module axi_aes_wrapper #(
    parameter DATA_WIDTH = 32,
    parameter ADDR_WIDTH = 32,
    parameter STRB_WIDTH = DATA_WIDTH/8,
    parameter ID_WIDTH = 8,
    parameter AWUSER_WIDTH = 1,
    parameter WUSER_WIDTH = 1,
    parameter BUSER_WIDTH = 1,
    parameter ARUSER_WIDTH = 1,
    parameter RUSER_WIDTH = 1
)(
    input wire clk,
    input wire rst,
    input wire [ID_WIDTH-1:0] s00_axi_awid,
    input wire [ADDR_WIDTH-1:0] s00_axi_awaddr,
    input wire [7:0] s00_axi_awlen,
    input wire [2:0] s00_axi_awsize,
    input wire [1:0] s00_axi_awburst,
    input wire  s00_axi_awlock,
    input wire [3:0] s00_axi_awcache,
    input wire [2:0] s00_axi_awprot,
    input wire [3:0] s00_axi_awqos,
    input wire [AWUSER_WIDTH-1:0] s00_axi_awuser,
    input wire  s00_axi_awvalid,
    output wire  s00_axi_awready,
    input wire [DATA_WIDTH-1:0] s00_axi_wdata,
    input wire [STRB_WIDTH-1:0] s00_axi_wstrb,
    input wire  s00_axi_wlast,
    input wire [WUSER_WIDTH-1:0] s00_axi_wuser,
    input wire  s00_axi_wvalid,
    output wire  s00_axi_wready,
    output wire [ID_WIDTH-1:0] s00_axi_bid,
    output wire [1:0] s00_axi_bresp,
    output wire [BUSER_WIDTH-1:0] s00_axi_buser,
    output wire  s00_axi_bvalid,
    input wire  s00_axi_bready,
    input wire [ID_WIDTH-1:0] s00_axi_arid,
    input wire [ADDR_WIDTH-1:0] s00_axi_araddr,
    input wire [7:0] s00_axi_arlen,
    input wire [2:0] s00_axi_arsize,
    input wire [1:0] s00_axi_arburst,
    input wire  s00_axi_arlock,
    input wire [3:0] s00_axi_arcache,
    input wire [2:0] s00_axi_arprot,
    input wire [3:0] s00_axi_arqos,
    input wire [ARUSER_WIDTH-1:0] s00_axi_aruser,
    input wire  s00_axi_arvalid,
    output wire  s00_axi_arready,
    output wire [ID_WIDTH-1:0] s00_axi_rid,
    output wire [DATA_WIDTH-1:0] s00_axi_rdata,
    output wire [1:0] s00_axi_rresp,
    output wire  s00_axi_rlast,
    output wire [RUSER_WIDTH-1:0] s00_axi_ruser,
    output wire  s00_axi_rvalid,
    input wire  s00_axi_rready,
    output wire aes_irq
);

    // Internal AXI M06 connection to AES. M00-M05/M07 are unused in this stage.
    output wire [ID_WIDTH-1:0] m06_axi_awid;
    output wire [ADDR_WIDTH-1:0] m06_axi_awaddr;
    output wire [7:0] m06_axi_awlen;
    output wire [2:0] m06_axi_awsize;
    output wire [1:0] m06_axi_awburst;
    output wire  m06_axi_awlock;
    output wire [3:0] m06_axi_awcache;
    output wire [2:0] m06_axi_awprot;
    output wire [3:0] m06_axi_awqos;
    output wire [3:0] m06_axi_awregion;
    output wire [AWUSER_WIDTH-1:0] m06_axi_awuser;
    output wire  m06_axi_awvalid;
    input wire  m06_axi_awready;
    output wire [DATA_WIDTH-1:0] m06_axi_wdata;
    output wire [STRB_WIDTH-1:0] m06_axi_wstrb;
    output wire  m06_axi_wlast;
    output wire [WUSER_WIDTH-1:0] m06_axi_wuser;
    output wire  m06_axi_wvalid;
    input wire  m06_axi_wready;
    input wire [ID_WIDTH-1:0] m06_axi_bid;
    input wire [1:0] m06_axi_bresp;
    input wire [BUSER_WIDTH-1:0] m06_axi_buser;
    input wire  m06_axi_bvalid;
    output wire  m06_axi_bready;
    output wire [ID_WIDTH-1:0] m06_axi_arid;
    output wire [ADDR_WIDTH-1:0] m06_axi_araddr;
    output wire [7:0] m06_axi_arlen;
    output wire [2:0] m06_axi_arsize;
    output wire [1:0] m06_axi_arburst;
    output wire  m06_axi_arlock;
    output wire [3:0] m06_axi_arcache;
    output wire [2:0] m06_axi_arprot;
    output wire [3:0] m06_axi_arqos;
    output wire [3:0] m06_axi_arregion;
    output wire [ARUSER_WIDTH-1:0] m06_axi_aruser;
    output wire  m06_axi_arvalid;
    input wire  m06_axi_arready;
    input wire [ID_WIDTH-1:0] m06_axi_rid;
    input wire [DATA_WIDTH-1:0] m06_axi_rdata;
    input wire [1:0] m06_axi_rresp;
    input wire  m06_axi_rlast;
    input wire [RUSER_WIDTH-1:0] m06_axi_ruser;
    input wire  m06_axi_rvalid;
    output wire  m06_axi_rready;

    axi_interconnect_wrap_2x8 #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .STRB_WIDTH(STRB_WIDTH),
        .ID_WIDTH(ID_WIDTH),
        .M06_BASE_ADDR(32'h1000_4000),
        .M06_ADDR_WIDTH({1{32'd12}})
    ) interconnect_inst (
        .clk(clk),
        .rst(rst),
        .s00_axi_awid(s00_axi_awid),
        .s00_axi_awaddr(s00_axi_awaddr),
        .s00_axi_awlen(s00_axi_awlen),
        .s00_axi_awsize(s00_axi_awsize),
        .s00_axi_awburst(s00_axi_awburst),
        .s00_axi_awlock(s00_axi_awlock),
        .s00_axi_awcache(s00_axi_awcache),
        .s00_axi_awprot(s00_axi_awprot),
        .s00_axi_awqos(s00_axi_awqos),
        .s00_axi_awuser(s00_axi_awuser),
        .s00_axi_awvalid(s00_axi_awvalid),
        .s00_axi_awready(s00_axi_awready),
        .s00_axi_wdata(s00_axi_wdata),
        .s00_axi_wstrb(s00_axi_wstrb),
        .s00_axi_wlast(s00_axi_wlast),
        .s00_axi_wuser(s00_axi_wuser),
        .s00_axi_wvalid(s00_axi_wvalid),
        .s00_axi_wready(s00_axi_wready),
        .s00_axi_bid(s00_axi_bid),
        .s00_axi_bresp(s00_axi_bresp),
        .s00_axi_buser(s00_axi_buser),
        .s00_axi_bvalid(s00_axi_bvalid),
        .s00_axi_bready(s00_axi_bready),
        .s00_axi_arid(s00_axi_arid),
        .s00_axi_araddr(s00_axi_araddr),
        .s00_axi_arlen(s00_axi_arlen),
        .s00_axi_arsize(s00_axi_arsize),
        .s00_axi_arburst(s00_axi_arburst),
        .s00_axi_arlock(s00_axi_arlock),
        .s00_axi_arcache(s00_axi_arcache),
        .s00_axi_arprot(s00_axi_arprot),
        .s00_axi_arqos(s00_axi_arqos),
        .s00_axi_aruser(s00_axi_aruser),
        .s00_axi_arvalid(s00_axi_arvalid),
        .s00_axi_arready(s00_axi_arready),
        .s00_axi_rid(s00_axi_rid),
        .s00_axi_rdata(s00_axi_rdata),
        .s00_axi_rresp(s00_axi_rresp),
        .s00_axi_rlast(s00_axi_rlast),
        .s00_axi_ruser(s00_axi_ruser),
        .s00_axi_rvalid(s00_axi_rvalid),
        .s00_axi_rready(s00_axi_rready),
        .s01_axi_awid(0),
        .s01_axi_awaddr(0),
        .s01_axi_awlen(0),
        .s01_axi_awsize(0),
        .s01_axi_awburst(0),
        .s01_axi_awlock(0),
        .s01_axi_awcache(0),
        .s01_axi_awprot(0),
        .s01_axi_awqos(0),
        .s01_axi_awuser(0),
        .s01_axi_awvalid(0),
        .s01_axi_wdata(0),
        .s01_axi_wstrb(0),
        .s01_axi_wlast(0),
        .s01_axi_wuser(0),
        .s01_axi_wvalid(0),
        .s01_axi_bready(0),
        .s01_axi_arid(0),
        .s01_axi_araddr(0),
        .s01_axi_arlen(0),
        .s01_axi_arsize(0),
        .s01_axi_arburst(0),
        .s01_axi_arlock(0),
        .s01_axi_arcache(0),
        .s01_axi_arprot(0),
        .s01_axi_arqos(0),
        .s01_axi_aruser(0),
        .s01_axi_arvalid(0),
        .s01_axi_rready(0),
        .m00_axi_awready(0),
        .m00_axi_wready(0),
        .m00_axi_bid(0),
        .m00_axi_bresp(0),
        .m00_axi_buser(0),
        .m00_axi_bvalid(0),
        .m00_axi_arready(0),
        .m00_axi_rid(0),
        .m00_axi_rdata(0),
        .m00_axi_rresp(0),
        .m00_axi_rlast(0),
        .m00_axi_ruser(0),
        .m00_axi_rvalid(0),
        .m01_axi_awready(0),
        .m01_axi_wready(0),
        .m01_axi_bid(0),
        .m01_axi_bresp(0),
        .m01_axi_buser(0),
        .m01_axi_bvalid(0),
        .m01_axi_arready(0),
        .m01_axi_rid(0),
        .m01_axi_rdata(0),
        .m01_axi_rresp(0),
        .m01_axi_rlast(0),
        .m01_axi_ruser(0),
        .m01_axi_rvalid(0),
        .m02_axi_awready(0),
        .m02_axi_wready(0),
        .m02_axi_bid(0),
        .m02_axi_bresp(0),
        .m02_axi_buser(0),
        .m02_axi_bvalid(0),
        .m02_axi_arready(0),
        .m02_axi_rid(0),
        .m02_axi_rdata(0),
        .m02_axi_rresp(0),
        .m02_axi_rlast(0),
        .m02_axi_ruser(0),
        .m02_axi_rvalid(0),
        .m03_axi_awready(0),
        .m03_axi_wready(0),
        .m03_axi_bid(0),
        .m03_axi_bresp(0),
        .m03_axi_buser(0),
        .m03_axi_bvalid(0),
        .m03_axi_arready(0),
        .m03_axi_rid(0),
        .m03_axi_rdata(0),
        .m03_axi_rresp(0),
        .m03_axi_rlast(0),
        .m03_axi_ruser(0),
        .m03_axi_rvalid(0),
        .m04_axi_awready(0),
        .m04_axi_wready(0),
        .m04_axi_bid(0),
        .m04_axi_bresp(0),
        .m04_axi_buser(0),
        .m04_axi_bvalid(0),
        .m04_axi_arready(0),
        .m04_axi_rid(0),
        .m04_axi_rdata(0),
        .m04_axi_rresp(0),
        .m04_axi_rlast(0),
        .m04_axi_ruser(0),
        .m04_axi_rvalid(0),
        .m05_axi_awready(0),
        .m05_axi_wready(0),
        .m05_axi_bid(0),
        .m05_axi_bresp(0),
        .m05_axi_buser(0),
        .m05_axi_bvalid(0),
        .m05_axi_arready(0),
        .m05_axi_rid(0),
        .m05_axi_rdata(0),
        .m05_axi_rresp(0),
        .m05_axi_rlast(0),
        .m05_axi_ruser(0),
        .m05_axi_rvalid(0),
        .m06_axi_awid(m06_axi_awid),
        .m06_axi_awaddr(m06_axi_awaddr),
        .m06_axi_awlen(m06_axi_awlen),
        .m06_axi_awsize(m06_axi_awsize),
        .m06_axi_awburst(m06_axi_awburst),
        .m06_axi_awlock(m06_axi_awlock),
        .m06_axi_awcache(m06_axi_awcache),
        .m06_axi_awprot(m06_axi_awprot),
        .m06_axi_awqos(m06_axi_awqos),
        .m06_axi_awregion(m06_axi_awregion),
        .m06_axi_awuser(m06_axi_awuser),
        .m06_axi_awvalid(m06_axi_awvalid),
        .m06_axi_awready(m06_axi_awready),
        .m06_axi_wdata(m06_axi_wdata),
        .m06_axi_wstrb(m06_axi_wstrb),
        .m06_axi_wlast(m06_axi_wlast),
        .m06_axi_wuser(m06_axi_wuser),
        .m06_axi_wvalid(m06_axi_wvalid),
        .m06_axi_wready(m06_axi_wready),
        .m06_axi_bid(m06_axi_bid),
        .m06_axi_bresp(m06_axi_bresp),
        .m06_axi_buser(m06_axi_buser),
        .m06_axi_bvalid(m06_axi_bvalid),
        .m06_axi_bready(m06_axi_bready),
        .m06_axi_arid(m06_axi_arid),
        .m06_axi_araddr(m06_axi_araddr),
        .m06_axi_arlen(m06_axi_arlen),
        .m06_axi_arsize(m06_axi_arsize),
        .m06_axi_arburst(m06_axi_arburst),
        .m06_axi_arlock(m06_axi_arlock),
        .m06_axi_arcache(m06_axi_arcache),
        .m06_axi_arprot(m06_axi_arprot),
        .m06_axi_arqos(m06_axi_arqos),
        .m06_axi_arregion(m06_axi_arregion),
        .m06_axi_aruser(m06_axi_aruser),
        .m06_axi_arvalid(m06_axi_arvalid),
        .m06_axi_arready(m06_axi_arready),
        .m06_axi_rid(m06_axi_rid),
        .m06_axi_rdata(m06_axi_rdata),
        .m06_axi_rresp(m06_axi_rresp),
        .m06_axi_rlast(m06_axi_rlast),
        .m06_axi_ruser(m06_axi_ruser),
        .m06_axi_rvalid(m06_axi_rvalid),
        .m06_axi_rready(m06_axi_rready),
        .m07_axi_awready(0),
        .m07_axi_wready(0),
        .m07_axi_bid(0),
        .m07_axi_bresp(0),
        .m07_axi_buser(0),
        .m07_axi_bvalid(0),
        .m07_axi_arready(0),
        .m07_axi_rid(0),
        .m07_axi_rdata(0),
        .m07_axi_rresp(0),
        .m07_axi_rlast(0),
        .m07_axi_ruser(0),
        .m07_axi_rvalid(0)
    );

    aes_axi_slave #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .STRB_WIDTH(STRB_WIDTH),
        .ID_WIDTH(ID_WIDTH)
    ) aes_inst (
        .s_axi_awid(m06_axi_awid),
        .s_axi_awaddr(m06_axi_awaddr),
        .s_axi_awlen(m06_axi_awlen),
        .s_axi_awsize(m06_axi_awsize),
        .s_axi_awburst(m06_axi_awburst),
        .s_axi_awlock(m06_axi_awlock),
        .s_axi_awcache(m06_axi_awcache),
        .s_axi_awprot(m06_axi_awprot),
        .s_axi_awqos(m06_axi_awqos),
        .s_axi_awuser(m06_axi_awuser),
        .s_axi_awvalid(m06_axi_awvalid),
        .s_axi_awready(m06_axi_awready),
        .s_axi_wdata(m06_axi_wdata),
        .s_axi_wstrb(m06_axi_wstrb),
        .s_axi_wlast(m06_axi_wlast),
        .s_axi_wuser(m06_axi_wuser),
        .s_axi_wvalid(m06_axi_wvalid),
        .s_axi_wready(m06_axi_wready),
        .s_axi_bid(m06_axi_bid),
        .s_axi_bresp(m06_axi_bresp),
        .s_axi_buser(m06_axi_buser),
        .s_axi_bvalid(m06_axi_bvalid),
        .s_axi_bready(m06_axi_bready),
        .s_axi_arid(m06_axi_arid),
        .s_axi_araddr(m06_axi_araddr),
        .s_axi_arlen(m06_axi_arlen),
        .s_axi_arsize(m06_axi_arsize),
        .s_axi_arburst(m06_axi_arburst),
        .s_axi_arlock(m06_axi_arlock),
        .s_axi_arcache(m06_axi_arcache),
        .s_axi_arprot(m06_axi_arprot),
        .s_axi_arqos(m06_axi_arqos),
        .s_axi_aruser(m06_axi_aruser),
        .s_axi_arvalid(m06_axi_arvalid),
        .s_axi_arready(m06_axi_arready),
        .s_axi_rid(m06_axi_rid),
        .s_axi_rdata(m06_axi_rdata),
        .s_axi_rresp(m06_axi_rresp),
        .s_axi_rlast(m06_axi_rlast),
        .s_axi_ruser(m06_axi_ruser),
        .s_axi_rvalid(m06_axi_rvalid),
        .s_axi_rready(m06_axi_rready),
        .aes_irq(aes_irq)
    );

endmodule

`default_nettype wire
